# encoding: UTF-8
# implement interface test script users-random_username
TargetService: 
plan_name: 'Interfaces_users-random_username'
owner: gang.wu@istuary.com
status: completed
created_dt: 2016-08-22
version: 1
last_modified_dt: 2016-08-22
timeout: 1200
actions: action_1

api_path: /api/mobile/v1/users/random_username
user:
  mobile: '18980709020'
  password: '123456'
unsign_test:
  - request: {}
    expected:
      code: 1
      message: ''
signin_test: 
  - request: {}
    expected:
      code: 1
      message: ''

            