# encoding: UTF-8
# implement interface test script notifications-unread_count
TargetService: 
plan_name: 'Interfaces_notifications-unread_count'
owner: gang.wu@istuary.com
status: completed
created_dt: 2016-08-22
version: 1
last_modified_dt: 2016-08-22
timeout: 1200
actions: action_1

#未读消息数量
api_path: /api/mobile/v1/notifications/unread_count
user:
  mobile: '18980709020'
  password: '123456'
unsign_test:
  - request: {}
    expected:
      code: 1
      message: ''
signin_test: 
  - request: {}
    expected:
      code: 1
      message: ''
            