# encoding: UTF-8
# implement interface test script web-articles-create
TargetService: 
plan_name: 'Interfaces_web-articles-create'
owner: gang.wu@istuary.com
status: completed
created_dt: 2016-08-22
version: 1
last_modified_dt: 2016-08-22
timeout: 1200
actions: action_1

api_path: /api/website/articles/create
user:
  mobile: '15800000002'
  password: '123456'
unsign_test:
  - request:
      post_title: '测试发表文章'
      post_content: '这里是文章内容'
      topics: 'abc;eds'
    expected:
      code: 401
      message: '请重新登录'
signin_test:
  - request:
      post_title: '测试发表文章'
      post_content: '这里是文章内容'
      topics: 'abc;eds'
    expected:
      code: 1
      message: '发布成功'
  - request:
      post_title: '测试发表文章'
      post_content: '这里是文章内容'
      topics: 'abc;eds'
    expected:
      code: 1001
      message: '此标题已使用，请更换'          