# encoding: UTF-8
# implement interface test script web-articles-show
TargetService: 
plan_name: 'Interfaces_web-articles-show'
owner: gang.wu@istuary.com
status: completed
created_dt: 2016-08-22
version: 1
last_modified_dt: 2016-08-22
timeout: 1200
actions: action_1

api_path: /api/website/articles/show
user:
  mobile: '15800000002'
  password: '123456'
unsign_test:
  - request:
      post_id: '0'
    expected:
      code: 1
      message: ''
  - request:
      post_id: '-1'
    expected:
      code: 1001
      message: '资源不存在或者已经删除'
signin_test:
  - request:
      post_id: '0'
    expected:
      code: 1
      message: ''
  - request:
      post_id: '-1'
    expected:
      code: 1001
      message: '资源不存在或者已经删除'
            