# encoding: UTF-8
TargetService: 
plan_name: 'Interfaces_articles_comments'
owner: gang.wu@istuary.com
status: completed
created_dt: 2016-08-22
version: 1
last_modified_dt: 2016-08-22
timeout: 1200
actions: action_1

api_path: /api/mobile/v1/articles/comments
user:
  mobile: '18980709020'
  password: '123456'
unsign_test:
  #时间排序
  - request:
      sort: '0'
      article_id: '0'
      page: '1'
    expected:
      code: 1
      message: ''
  #点赞排序
  - request:
      sort: '1'
      article_id: '0'
      page: '1'
    expected:
      code: 1
      message: ''
  #文章不存在
  - request:
      sort: '1'
      article_id: '-1'
      page: '1'
    expected:
      code: 1001
      message: '资源不存在或者已经删除'
signin_test: 
  #时间排序
  - request:
      sort: '0'
      article_id: '0'
      page: '1'
    expected:
      code: 1
      message: ''
  #点赞排序
  - request:
      sort: '1'
      article_id: '0'
      page: '1'
    expected:
      code: 1
      message: ''
  #文章不存在
  - request:
      sort: '1'
      article_id: '-1'
      page: '1'
    expected:
      code: 1001
      message: '资源不存在或者已经删除'

            