# encoding: UTF-8
# implement interface test script notifications-read_all
TargetService: 
plan_name: 'Interfaces_notifications-read_all'
owner: gang.wu@istuary.com
status: completed
created_dt: 2016-08-22
version: 1
last_modified_dt: 2016-08-22
timeout: 1200
actions: action_1

# 消息全部已读
api_path: /api/mobile/v1/notifications/read_all
user:
  mobile: '18980709020'
  password: '123456'
unsign_test:
  - request: {}
    expected:
      code: 401
      message: '请重新登录'
signin_test: 
  - request: {}
    expected:
      code: 1
      message: '消息设置已读成功'
            