# encoding: UTF-8
# implement interface test script admin-features-uptoken
TargetService: 
plan_name: 'Interfaces_admin-features-uptoken'
owner: gang.wu@istuary.com
status: completed
created_dt: 2016-10-14
version: 1
last_modified_dt: 2016-10-14
timeout: 1200
actions: action_1

api_path: /api/admin/features/uptoken
user:
  user_name: 'smart'
  password: '123456'
unsign_test:
  - request: {}
    expected:
      code: 401
      message: '请重新登录'
signin_test: 
  - request: {}
    expected:
      code: 1
      message: ''
            