# encoding: UTF-8
# implement interface test script notifications-show
TargetService: 
plan_name: 'Interfaces_notifications-show'
owner: gang.wu@istuary.com
status: completed
created_dt: 2016-08-22
version: 1
last_modified_dt: 2016-08-22
timeout: 1200
actions: action_1

#获取消息详情
api_path: /api/mobile/v1/notifications/show
user:
  mobile: '18980709020'
  password: '123456'
export_user:
  mobile: '15800000002'
  password: '123456'
unsign_test:
  - request:
      notification_id: '50'
      page: '1'
    expected:
      code: 401
      message: '请重新登录'
signin_test: 
  - request:
      notification_id: '-1'
      page: '1'
    expected:
      code: 1001
      message: '资源不存在或者已经删除'
  - request:
      notification_id: '0'
      page: '1'
    expected:
      code: 1001
      message: '您没有权限进行此操作'
  - request:
      notification_id: '1'
      page: '1'
    expected:
      code: 1
      message: ''        