# encoding: UTF-8
# implement interface test script users-show
TargetService: 
plan_name: 'Interfaces_users-show'
owner: gang.wu@istuary.com
status: completed
created_dt: 2016-08-22
version: 1
last_modified_dt: 2016-08-22
timeout: 1200
actions: action_1

#获取个人信息
api_path: /api/mobile/v1/users/show
user:
  mobile: '18980709020'
  password: '123456'
unsign_test:
  - request:
      user_id: '23'
    expected:
      code: 1
      message: ''
signin_test: 
  - request:
      user_id: '23'
    expected:
      code: 1
      message: ''
  - request:
      user_id: '23'
    expected:
      code: 1
      message: ''
      is_expert: 0
  - request:
      user_id: '8'
    expected:
      code: 1
      message: ''
      is_expert: 1
            