# encoding: UTF-8
# implement interface test script web-users-show
TargetService: 
plan_name: 'Interfaces_web-users-show'
owner: gang.wu@istuary.com
status: completed
created_dt: 2016-08-22
version: 1
last_modified_dt: 2016-08-22
timeout: 1200
actions: action_1

api_path: /api/website/users/show
user:
  mobile: '18980709020'
  password: '123456'
export_user:
  mobile: '15800000002'
  password: '123456'
unsign_test:
  - request: {}
    expected:
      code: 401
      message: '请重新登录'
signin_test:
  - request: {}
    expected:
      is_expert: 0
      code: 1
      message: ''
  - request: {}
    expected:
      is_expert: 1
      code: 1
      message: ''  
            