# encoding: UTF-8
# implement interface test script admin-features-save_anchor_data
TargetService: 
plan_name: 'Interfaces_admin-features-save_anchor_data'
owner: gang.wu@istuary.com
status: completed
created_dt: 2016-10-14
version: 1
last_modified_dt: 2016-10-14
timeout: 1200
actions: action_1

api_path: /api/admin/features/save_anchor_data
user:
  user_name: 'smart'
  password: '123456'
precodition:
  - api_path: /api/admin/features/create
    request: 
      title: '专题16101801'
      cover: 'o_1at7r0po78vqf3312ci7v3uds2t.png'
      cover_thumbnail: 'o_1at7r0diidvqnan1v6mkssin32o.png'
      description: ''
      start_time: '2016-10-17'
      end_time: ''
  - api_path: /api/admin/features/create_anchor
    request: 
      feature_id: ''
      name: '锚点分组1'
  - api_path: /api/admin/features/create_anchor
    request: 
      feature_id: ''
      name: '锚点分组2'
  - api_path: /api/admin/searches/articles
    request:
      keyword: ''
      page: '1'
      per: '5' 
  - api_path: /api/admin/searches/topics
    request:
      keyword: ''
      page: '1'
      per: '5' 
unsign_test:
  - request: 
      feature_id: '1'
      data: ''
    expected:
      code: 401
      message: '请重新登录'
signin_test: 
  - request: 
      feature_id: '0'
      data: '0'
    expected:
      code: 1
      message: '保存锚点数据成功'
  - request: 
      feature_id: '0'
      data: '@#$%^&|!@#$^&'
    expected:
      code: 1001
      message: '资源不存在或者已经删除'
  - request: 
      feature_id: '-1'
      data: '0'
    expected:
      code: 1001
      message: '资源不存在或者已经删除'
  - request: 
      feature_id: 
      data: 
    expected:
      code: 1001
      message: '资源不存在或者已经删除' 
  - request: 
      feature_id: '0'
      data: '-1:1=1,1=2'
    expected:
      code: 1001
      message: '资源不存在或者已经删除'  
  - request: 
      feature_id: '0'
      data: ''
    expected:
      code: 1
      message: '保存锚点数据成功'  
  - request: 
      feature_id: '0'
      data: '1:-1=1,-2=2'
    expected:
      code: 1001
      message: '资源不存在或者已经删除'
                  