# encoding: UTF-8
# implement interface test script web-topics-list
TargetService: 
plan_name: 'Interfaces_web-topics-list'
owner: gang.wu@istuary.com
status: completed
created_dt: 2016-10-10
version: 1
last_modified_dt: 2016-10-10
timeout: 1200
actions: action_1

api_path: /api/website/topics/list
user:
  mobile: '15800000002'
  password: '123456'
unsign_test:
  - request:
      keyword: 'test'
    expected:
      code: 401
      message: '请重新登录'
signin_test:
  - request:
      keyword: '安全'
    expected:
      code: 1
      message: ''
      length: 5
  - request:
      keyword: ''
    expected:
      code: 1
      message: ''
      length: 5
  - request:
      keyword: '无搜索结果的话题'
    expected:
      code: 1
      message: ''
      length: 0         