# encoding: UTF-8
# implement interface test script web-articles-uptoken
TargetService: 
plan_name: 'Interfaces_web-articles-uptoken'
owner: gang.wu@istuary.com
status: completed
created_dt: 2016-08-22
version: 1
last_modified_dt: 2016-08-22
timeout: 1200
actions: action_1

api_path: /api/website/articles/uptoken
user:
  mobile: '15800000002'
  password: '123456'
unsign_test:
  - request: {}
    expected:
      code: 401
      message: '请重新登录'
signin_test:
  - request: {}
    expected:
      code: 1
      message: ''
            