# encoding: UTF-8
# implement interface test script web-articles-comments
TargetService: 
plan_name: 'Interfaces_web-articles-comments'
owner: gang.wu@istuary.com
status: completed
created_dt: 2016-10-10
version: 1
last_modified_dt: 2016-10-10
timeout: 1200
actions: action_1

api_path: /api/website/articles/comments
user:
  mobile: '15800000002'
  password: '123456'
unsign_test:
  #时间排序
  - request:
      sort: '0'
      post_id:  '0'
      page: '1'
    expected:
      code: 1
      message: ''
  #时间排序
  - request:
      sort: '0'
      post_id:  '0'
      page: '1'
      per: '10'
    expected:
      code: 1
      message: ''
  #点赞排序
  - request:
      sort: '1'
      post_id:  '0'
      page: '1'
      per: '6'
    expected:
      code: 1
      message: ''
  #文章不存在
  - request:
      sort: '1'
      post_id:  '-1'
      page: '1'
      per: '6'
    expected:
      code: 1001
      message: '资源不存在或者已经删除'
signin_test: 
  #时间排序
  - request:
      sort: '0'
      post_id:  '0'
      page: '1'
    expected:
      code: 1
      message: ''
  #时间排序
  - request:
      sort: '0'
      post_id:  '0'
      page: '1'
      per: '6'
    expected:
      code: 1
      message: ''
  #点赞排序
  - request:
      sort: '1'
      post_id:  '0'
      page: '1'
      per: '10'
    expected:
      code: 1
      message: ''
  #文章不存在
  - request:
      sort: '1'
      post_id:  '-1'
      page: '1'
      per: '10'
    expected:
      code: 1001
      message: '资源不存在或者已经删除'
             