# encoding: UTF-8
# implement interface test script mobile-web-banners-index
TargetService: 
plan_name: 'Interfaces_mobile-web-banners-index'
owner: gang.wu@istuary.com
status: completed
created_dt: 2016-08-22
version: 1
last_modified_dt: 2016-08-22
timeout: 1200
actions: action_1

api_path: /api/h5/banners/index
user:
  mobile: '15800000002'
  password: '123456'
unsign_test:
  - request: {}
    expected:
      code: 1
      message: ''
             